project_name: "FeatureMap"
base_dir: .
source_url: https://github.com/CottageLabs/FeatureMap/tree/main
exclude:
  - "*.pyc"
  - "*.png"
  - "*.gif"
  - "*.jpg"
  - "*.ico"
  - "*.jpeg"
  - "README.md"
  - ".gitignore"
  - "requirements.txt"
  - "setup.py"
  - "LICENSE"
exclude_dirs:
  - .featuremap
  - .git
  - .idea
  - example
  - docs/map
  - featuremap.egg-info
#include: # No need for any overrides to the exclude directive
ignore_parse_errors:
  - noop
delimiter: ~~
types: .featuremap/types.csv
type_validation: error
terminals: .featuremap/terminals.csv
out_dir: docs/map
serialisers:
  - class: featuremap.jsonserialiser.JSONSerialiser
    dir: json
  - class: featuremap.csvserialiser.CSVSerialiser
    dir: csv
  - class: featuremap.htmlserialiser.HTMLSerialiser
    dir: html
    template_dirs:
      - resources/htmlserialiser/templates
    templates:
      relationships: relationships.html
      entities: entities.html
      files: files.html
      no-downstream: no-downstream.html
      unexpected-downstream: unexpected-downstream.html
      unseen-terminals: unseen-terminals.html